# Generated by Django 5.2.9 on 2026-01-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRM', 'Confirm'), ('CANCEL', 'Cancel')], default='PENDING', max_length=20),
        ),
    ]
