# Generated by Django 5.2.9 on 2026-01-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_image',
            field=models.FileField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
