# Generated by Django 5.2.4 on 2025-11-03 06:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('welcome_message', models.TextField(blank=True, default='')),
                ('agent_prompt', models.TextField(help_text='System/instructions for the agent')),
                ('business_details', models.JSONField(blank=True, default=dict)),
                ('voice', models.CharField(default='alloy', max_length=50)),
                ('language', models.CharField(default='bn', max_length=10)),
                ('enabled', models.BooleanField(default=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('theme_primary', models.CharField(default='#16a34a', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'updated_at'], name='voice_agent_owner_i_8a673f_idx')],
            },
        ),
    ]
