# Generated by Django 5.2.9 on 2026-01-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='full_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('superuser', 'Superuser'), ('staff', 'Staff'), ('seller', 'Seller'), ('sub_seller', 'Sub Seller'), ('reseller', 'Reseller'), ('sub_reseller', 'Sub_Reseller'), ('merchant', 'Merchant'), ('sub_merchant', 'Sub Merchant')], default='user', max_length=255),
        ),
    ]
