# Generated by Django 5.2.9 on 2026-01-07 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='username',
            new_name='user_str_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_name',
        ),
    ]
