<<<<<<< HEAD
# Generated by Django 5.2.9 on 2026-01-17 10:32
=======
# Generated by Django 5.2.9 on 2026-01-17 09:45
>>>>>>> 7c9ae9b11d32523fe66d9d1aa9cd5b991ed7b8b9

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_full_name_account_name_alter_account_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='name',
            new_name='full_name',
        ),
    ]
