# Generated by Django 5.2.9 on 2026-01-26 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_name_account_full_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
