# Generated by Django 5.2.9 on 2025-12-16 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedCaption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(blank=True, max_length=500, null=True)),
                ('image_description', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn')], default='instagram', max_length=50)),
                ('tone', models.CharField(choices=[('friendly', 'Friendly'), ('formal', 'Formal'), ('funny', 'Funny'), ('serious', 'Serious')], default='friendly', max_length=50)),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('call_to_action', models.CharField(blank=True, max_length=255, null=True)),
                ('captions', models.JSONField(blank=True, default=list)),
                ('selected_caption', models.TextField(blank=True, null=True)),
                ('formatted_caption', models.TextField(blank=True, null=True)),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('character_count', models.PositiveIntegerField(default=0)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('within_limit', models.BooleanField(default=True)),
                ('max_length', models.PositiveIntegerField(default=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
