# Generated by Django 5.2.9 on 2026-02-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedcaption",
            name="platform",
            field=models.CharField(
                choices=[
                    ("instagram", "Instagram"),
                    ("facebook", "Facebook"),
                    ("twitter", "Twitter"),
                    ("linkedin", "LinkedIn"),
                    ("tiktok", "TikTok"),
                ],
                default="instagram",
                max_length=50,
            ),
        ),
    ]
