# Generated by Django 5.2.9 on 2026-01-14 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popup', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recharge',
        ),
    ]
