# Generated by Django 5.2.8 on 2025-11-18 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sid', models.CharField(max_length=255)),
                ('call_status', models.CharField(max_length=50)),
                ('call_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('caller', models.CharField(blank=True, max_length=50, null=True)),
                ('callee', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=100, null=True)),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='assistant.assistant')),
            ],
            options={
                'db_table': 'call_calllog',
                'indexes': [models.Index(fields=['assistant', 'timestamp'], name='call_calllo_assista_888f8a_idx')],
            },
        ),
    ]
