# Generated by Django 5.2.8 on 2025-11-18 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_initial'),
        ('call', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='assistant.assistant'),
        ),
    ]
