# Generated by Django 5.2.8 on 2025-11-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0002_alter_calllog_assistant'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='record_sid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
