# Generated by Django 5.2.8 on 2025-11-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0003_calllog_record_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10, null=True),
        ),
    ]
