# Generated by Django 5.2.8 on 2025-11-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0004_calllog_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='direction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
