# Generated by Django 5.2.9 on 2026-01-13 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productitem',
            old_name='Product',
            new_name='product',
        ),
    ]
