# Generated by Django 5.2.9 on 2026-01-04 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_productpurchase_productpurchaseitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='name',
            new_name='colors',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='name',
            new_name='size',
        ),
    ]
