# Generated by Django 5.2.9 on 2026-01-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stock_stockmovement_delete_color_delete_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
