# Generated by Django 5.2.9 on 2026-01-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_productitem_barcode_productitem_qr_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
