# Generated by Django 5.2.9 on 2026-01-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_productpurchase_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sizes',
        ),
        migrations.AddField(
            model_name='order',
            name='colors',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sizes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
