# Generated by Django 5.2.9 on 2026-01-13 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_productitem_color_alter_productitem_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening', models.PositiveIntegerField(default=0)),
                ('purchase', models.PositiveIntegerField(default=0)),
                ('sales', models.PositiveIntegerField(default=0)),
                ('returns', models.PositiveIntegerField(default=0)),
                ('damage', models.PositiveIntegerField(default=0)),
                ('product_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_item', to='inventory.productitem')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stock')),
            ],
        ),
    ]
