# Generated by Django 5.2.9 on 2026-01-06 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_order_colors_remove_order_sizes_order_colors_and_more'),
        ('vendor', '0005_rename_vendor_name_vendorinvoice_vendor_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Product',
        ),
    ]
