# Generated by Django 5.2.9 on 2026-01-15 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_stockitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_price',
        ),
        migrations.RemoveField(
            model_name='productpurchaseitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productpurchaseitem',
            name='total',
        ),
        migrations.RemoveField(
            model_name='productpurchaseitem',
            name='unit_cost',
        ),
        migrations.RemoveField(
            model_name='productpurchaseitem',
            name='variant',
        ),
        migrations.AddField(
            model_name='productpurchase',
            name='items',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='productpurchase',
            name='purchase_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productpurchase',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productpurchaseitem',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='inventory.productpurchase'),
        ),
        migrations.AlterField(
            model_name='productpurchaseitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
