# Generated by Django 5.2.9 on 2026-01-15 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_purchasereturn_purchasereturnitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasereturn',
            name='vendor',
        ),
    ]
