# Generated by Django 5.2.9 on 2026-01-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_purchasereturn_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpurchase',
            name='total_acount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
