# Generated by Django 5.2.9 on 2026-01-15 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_productpurchase_total_acount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='product_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_item', to='inventory.productitem'),
        ),
    ]
