# Generated by Django 5.2.9 on 2026-01-17 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_stockitem_product_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='LossAndDamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('damage_date', models.DateField(auto_now_add=True)),
                ('damage_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loss_and_damage', to='inventory.productpurchase')),
            ],
        ),
        migrations.CreateModel(
            name='LossAndDamageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('condition_notes', models.TextField(blank=True, null=True)),
                ('loss_and_damage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.lossanddamage')),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productitem')),
            ],
        ),
    ]
