# Generated by Django 5.2.9 on 2026-01-17 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_lossanddamage_lossanddamageitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lossanddamage',
            name='purchase_order',
        ),
        migrations.AddField(
            model_name='lossanddamage',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='loss_and_damage', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
