# Generated by Django 5.2.8 on 2025-11-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('topup', 'Topup'), ('call', 'Call'), ('agent', 'Agent'), ('number', 'Number'), ('support', 'Support'), ('other', 'Other')], max_length=100),
        ),
    ]
