# Generated by Django 5.2.8 on 2025-11-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPricePerMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Agent Price Per Month',
                'verbose_name_plural': 'Agent Price Per Month',
            },
        ),
        migrations.CreateModel(
            name='CallCostPerMinute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Call Cost Per Minute',
                'verbose_name_plural': 'Call Cost Per Minute',
            },
        ),
        migrations.CreateModel(
            name='MinimumTopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Minimum Topup',
                'verbose_name_plural': 'Minimum Topup',
            },
        ),
    ]
