# Generated by Django 6.0 on 2025-12-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaperflyMerchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(max_length=255)),
                ('product_nature', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('thana', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_branch', models.CharField(max_length=255)),
                ('routing_number', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_mode', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaperflyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchantCode', models.CharField(max_length=50)),
                ('merOrderRef', models.CharField(max_length=50)),
                ('pickMerchantName', models.CharField(blank=True, max_length=255, null=True)),
                ('pickMerchantAddress', models.TextField(blank=True, null=True)),
                ('pickMerchantThana', models.CharField(blank=True, max_length=255, null=True)),
                ('pickMerchantDistrict', models.CharField(blank=True, max_length=255, null=True)),
                ('pickupMerchantPhone', models.CharField(blank=True, max_length=50, null=True)),
                ('productSizeWeight', models.CharField(max_length=50)),
                ('productBrief', models.CharField(blank=True, max_length=255, null=True)),
                ('packagePrice', models.CharField(max_length=50)),
                ('deliveryOption', models.CharField(max_length=50)),
                ('custname', models.CharField(max_length=255)),
                ('custaddress', models.TextField()),
                ('customerThana', models.CharField(blank=True, max_length=255, null=True)),
                ('customerDistrict', models.CharField(max_length=255)),
                ('custPhone', models.CharField(max_length=50)),
                ('max_weight', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
