# Generated by Django 6.0 on 2025-12-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperflyOrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReferenceNumber', models.CharField(max_length=50)),
                ('merchantCode', models.CharField(max_length=50)),
                ('Pick', models.CharField(blank=True, max_length=255, null=True)),
                ('PickTime', models.CharField(blank=True, max_length=50, null=True)),
                ('inTransit', models.CharField(blank=True, max_length=255, null=True)),
                ('inTransitTime', models.CharField(blank=True, max_length=50, null=True)),
                ('ReceivedAtPoint', models.CharField(blank=True, max_length=255, null=True)),
                ('ReceivedAtPointTime', models.CharField(blank=True, max_length=50, null=True)),
                ('PickedForDelivery', models.CharField(blank=True, max_length=255, null=True)),
                ('PickedForDeliveryTime', models.CharField(blank=True, max_length=50, null=True)),
                ('Delivered', models.CharField(blank=True, max_length=255, null=True)),
                ('DeliveredTime', models.CharField(blank=True, max_length=50, null=True)),
                ('Returned', models.CharField(blank=True, max_length=255, null=True)),
                ('ReturnedTime', models.CharField(blank=True, max_length=50, null=True)),
                ('Partial', models.CharField(blank=True, max_length=255, null=True)),
                ('PartialTime', models.CharField(blank=True, max_length=50, null=True)),
                ('onHoldSchedule', models.CharField(blank=True, max_length=255, null=True)),
                ('close', models.CharField(blank=True, max_length=255, null=True)),
                ('closeTime', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
