# Generated by Django 5.2.9 on 2026-01-04 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0001_initial'),
        ('orders', '0003_orderitem_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCourierMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_order_ref', models.CharField(help_text='Paperfly: merOrderRef | Steadfast: invoice/consignment_id | Pathao: merchant_order_id', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courier.courierlist')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courier_map', to='orders.order')),
            ],
        ),
    ]
