# Generated by Django 5.2.9 on 2026-01-05 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0002_ordercouriermap'),
        ('orders', '0003_orderitem_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperflyorder',
            name='pickMerchantAddress',
        ),
        migrations.RemoveField(
            model_name='paperflyorder',
            name='pickMerchantDistrict',
        ),
        migrations.RemoveField(
            model_name='paperflyorder',
            name='pickMerchantName',
        ),
        migrations.RemoveField(
            model_name='paperflyorder',
            name='pickMerchantThana',
        ),
        migrations.RemoveField(
            model_name='paperflyorder',
            name='pickupMerchantPhone',
        ),
        migrations.RemoveField(
            model_name='paperflyorder',
            name='productSizeWeight',
        ),
        migrations.CreateModel(
            name='CourierOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('tracking_code', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_status', models.CharField(blank=True, max_length=50, null=True)),
                ('merchant_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice', models.CharField(blank=True, max_length=100, null=True)),
                ('recipient_name', models.CharField(max_length=100)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('recipient_address', models.TextField()),
                ('payment_type', models.CharField(default='cod', max_length=50)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('delivery_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_orders', to='courier.courierlist')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courier_orders', to='orders.order')),
            ],
        ),
    ]
