# Generated by Django 6.0 on 2025-12-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0002_paperflyordertracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperflyorder',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
