# Generated by Django 5.2.9 on 2026-01-05 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0003_remove_paperflyorder_pickmerchantaddress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierOrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=50)),
                ('status_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courier_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_status', to='courier.courierorder')),
            ],
            options={
                'unique_together': {('courier_order', 'status')},
            },
        ),
    ]
