# Generated by Django 6.0 on 2025-12-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0003_paperflyorder_tracking_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperflyOrderCancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('merchantCode', models.CharField(max_length=50)),
                ('cancel_message', models.CharField(blank=True, max_length=255, null=True)),
                ('response_code', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
