# Generated by Django 5.2.9 on 2025-12-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0004_paperflyordercancel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SteadfastOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignment_id', models.BigIntegerField(blank=True, null=True)),
                ('invoice', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_code', models.CharField(blank=True, max_length=100, null=True)),
                ('recipient_name', models.CharField(max_length=100)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('recipient_address', models.TextField()),
                ('cod_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(default='in_review', max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('api_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SteadfastReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_id', models.BigIntegerField(blank=True, null=True)),
                ('consignment_id', models.BigIntegerField(blank=True, null=True)),
                ('invoice', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_code', models.CharField(blank=True, max_length=100, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('api_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SteadfastTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignment_id', models.BigIntegerField(blank=True, null=True)),
                ('invoice', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_code', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_status', models.CharField(max_length=50)),
                ('api_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
