# Generated by Django 5.2.9 on 2026-01-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0004_courierorderstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierorder',
            name='couriers_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
