# Generated by Django 5.2.9 on 2025-12-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0007_courierlist_usercourier'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierlist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
