# Generated by Django 5.2.8 on 2025-11-18 05:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('first_message_mode', models.CharField(choices=[('assistant speaks first', 'Assistant Speaks First'), ('assistant wait for user', 'Assistant Waits for User'), ('assistant speaks first with model generated message', 'Assistant Speaks First with Model Generated Message')], default='assistant speaks first', max_length=100)),
                ('first_message', models.TextField(blank=True, default='')),
                ('system_prompt', models.TextField(blank=True, default='')),
                ('voice', models.CharField(default='bn-BD-NabanitaNeural', max_length=100)),
                ('language', models.CharField(choices=[('af-ZA', 'Afrikaans (South Africa)'), ('am-ET', 'Amharic (Ethiopia)'), ('ar-AE', 'Arabic (U.A.E.)'), ('ar-BH', 'Arabic (Bahrain)'), ('ar-DZ', 'Arabic (Algeria)'), ('ar-EG', 'Arabic (Egypt)'), ('ar-IQ', 'Arabic (Iraq)'), ('ar-JO', 'Arabic (Jordan)'), ('ar-KW', 'Arabic (Kuwait)'), ('ar-LB', 'Arabic (Lebanon)'), ('ar-MA', 'Arabic (Morocco)'), ('ar-OM', 'Arabic (Oman)'), ('ar-QA', 'Arabic (Qatar)'), ('ar-SA', 'Arabic (Saudi Arabia)'), ('ar-TN', 'Arabic (Tunisia)'), ('ar-YE', 'Arabic (Yemen)'), ('az-AZ', 'Azerbaijani (Azerbaijan)'), ('bg-BG', 'Bulgarian (Bulgaria)'), ('bn-BD', 'Bangla (Bangladesh)'), ('bn-IN', 'Bangla (India)'), ('ca-ES', 'Catalan (Spain)'), ('cs-CZ', 'Czech (Czech Republic)'), ('da-DK', 'Danish (Denmark)'), ('de-DE', 'German (Germany)'), ('el-GR', 'Greek (Greece)'), ('en-AU', 'English (Australia)'), ('en-CA', 'English (Canada)'), ('en-GB', 'English (United Kingdom)'), ('en-IN', 'English (India)'), ('en-IE', 'English (Ireland)'), ('en-NZ', 'English (New Zealand)'), ('en-PH', 'English (Philippines)'), ('en-US', 'English (United States)'), ('en-ZA', 'English (South Africa)'), ('es-AR', 'Spanish (Argentina)'), ('es-BO', 'Spanish (Bolivia)'), ('es-CL', 'Spanish (Chile)'), ('es-CO', 'Spanish (Colombia)'), ('es-CR', 'Spanish (Costa Rica)'), ('es-DO', 'Spanish (Dominican Republic)'), ('es-EC', 'Spanish (Ecuador)'), ('es-ES', 'Spanish (Spain)'), ('es-GT', 'Spanish (Guatemala)'), ('es-HN', 'Spanish (Honduras)'), ('es-MX', 'Spanish (Mexico)'), ('es-NI', 'Spanish (Nicaragua)'), ('es-PA', 'Spanish (Panama)'), ('es-PE', 'Spanish (Peru)'), ('es-PR', 'Spanish (Puerto Rico)'), ('es-PY', 'Spanish (Paraguay)'), ('es-SV', 'Spanish (El Salvador)'), ('es-US', 'Spanish (United States)'), ('es-UY', 'Spanish (Uruguay)'), ('es-VE', 'Spanish (Venezuela)'), ('et-EE', 'Estonian (Estonia)'), ('eu-ES', 'Basque (Spain)'), ('fa-IR', 'Persian (Iran)'), ('fi-FI', 'Finnish (Finland)'), ('fil-PH', 'Filipino (Philippines)'), ('fr-BE', 'French (Belgium)'), ('fr-CA', 'French (Canada)'), ('fr-CH', 'French (Switzerland)'), ('fr-FR', 'French (France)'), ('gl-ES', 'Galician (Spain)'), ('gu-IN', 'Gujarati (India)'), ('he-IL', 'Hebrew (Israel)'), ('hi-IN', 'Hindi (India)'), ('hr-HR', 'Croatian (Croatia)'), ('hu-HU', 'Hungarian (Hungary)'), ('id-ID', 'Indonesian (Indonesia)'), ('is-IS', 'Icelandic (Iceland)'), ('it-CH', 'Italian (Switzerland)'), ('it-IT', 'Italian (Italy)'), ('ja-JP', 'Japanese (Japan)'), ('jv-ID', 'Javanese (Indonesia)'), ('kn-IN', 'Kannada (India)'), ('kk-KZ', 'Kazakh (Kazakhstan)'), ('km-KH', 'Khmer (Cambodia)'), ('ko-KR', 'Korean (South Korea)'), ('lo-LA', 'Lao (Laos)'), ('lt-LT', 'Lithuanian (Lithuania)'), ('lv-LV', 'Latvian (Latvia)'), ('mk-MK', 'Macedonian (North Macedonia)'), ('ml-IN', 'Malayalam (India)'), ('mn-MN', 'Mongolian (Mongolia)'), ('mr-IN', 'Marathi (India)'), ('ms-MY', 'Malay (Malaysia)'), ('my-MM', 'Myanmar (Burmese)'), ('ne-NP', 'Nepali (Nepal)'), ('nl-BE', 'Dutch (Belgium)'), ('nl-NL', 'Dutch (Netherlands)'), ('no-NO', 'Norwegian (Norway)'), ('pa-IN', 'Punjabi (India)'), ('pl-PL', 'Polish (Poland)'), ('pt-BR', 'Portuguese (Brazil)'), ('pt-PT', 'Portuguese (Portugal)'), ('ro-RO', 'Romanian (Romania)'), ('ru-RU', 'Russian (Russia)'), ('si-LK', 'Sinhala (Sri Lanka)'), ('sk-SK', 'Slovak (Slovakia)'), ('sl-SI', 'Slovenian (Slovenia)'), ('sr-RS', 'Serbian (Serbia)'), ('su-ID', 'Sundanese (Indonesia)'), ('sv-SE', 'Swedish (Sweden)'), ('sw-KE', 'Swahili (Kenya)'), ('ta-IN', 'Tamil (India)'), ('ta-LK', 'Tamil (Sri Lanka)'), ('te-IN', 'Telugu (India)'), ('th-TH', 'Thai (Thailand)'), ('tr-TR', 'Turkish (Turkey)'), ('uk-UA', 'Ukrainian (Ukraine)'), ('ur-PK', 'Urdu (Pakistan)'), ('uz-UZ', 'Uzbek (Uzbekistan)'), ('vi-VN', 'Vietnamese (Vietnam)'), ('zu-ZA', 'Zulu (South Africa)'), ('zh-CN', 'Chinese (Simplified, China)'), ('zh-HK', 'Chinese (Traditional, Hong Kong)'), ('zh-TW', 'Chinese (Traditional, Taiwan)')], default='bn', max_length=10)),
                ('enabled', models.BooleanField(default=False)),
                ('model', models.CharField(choices=[('gpt-5-turbo', 'GPT-5 Turbo'), ('gpt-4', 'GPT-4'), ('gpt-4o-mini', 'GPT-4O Mini'), ('gpt-4o-turbo', 'GPT-4O Turbo'), ('gpt-4o-32k', 'GPT-4O 32K'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo'), ('gpt-3.5-turbo-16k', 'GPT-3.5 Turbo 16K'), ('gpt-3.5-turbo-16k-0613', 'GPT-3.5 Turbo 16K 0613'), ('gpt-3.5-turbo-0613', 'GPT-3.5 Turbo 0613'), ('gpt-3.5-turbo-instruct', 'GPT-3.5 Turbo Instruct')], default='gpt-4o-mini', max_length=100)),
                ('max_tokens', models.IntegerField(default=250)),
                ('temperature', models.FloatField(default=0.7)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('theme_primary', models.CharField(default='#16a34a', max_length=20)),
                ('twilio_number', models.CharField(blank=True, default='', max_length=100)),
                ('crisis_keywords', models.TextField(blank=True, default='')),
                ('crisis_keywords_prompt', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('embed_html', models.TextField(blank=True, null=True)),
                ('eleven_agent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssistantFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='assistants/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssistantMamory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('ended_reason', models.CharField(choices=[('Customer ended call', 'Customer ended call'), ('Assistant ended call', 'Assistant ended call'), ('Assistand did not receive', 'Assistant did not receive')], default='user', max_length=100)),
                ('type', models.CharField(choices=[('chat', 'Chat'), ('voice', 'Voice'), ('web', 'Web'), ('call', 'Call')], default='chat', max_length=100)),
                ('successs_evalation', models.BooleanField(default=False)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('end_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('admin', 'Admin'), ('bot', 'Bot'), ('system', 'System'), ('error', 'Error'), ('unknown', 'Unknown')], max_length=100)),
                ('text', models.TextField()),
                ('chunk', models.TextField()),
                ('audio', models.FileField(upload_to='transcripts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
