# Generated by Django 5.2.8 on 2025-11-18 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assistantfile',
            name='assistant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='assistant.assistant'),
        ),
        migrations.AddField(
            model_name='assistantmamory',
            name='assistant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot_memory', to='assistant.assistant'),
        ),
        migrations.AddField(
            model_name='transcript',
            name='assistant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='assistant.assistant'),
        ),
        migrations.AddField(
            model_name='transcriptchunk',
            name='transcript',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='assistant.transcript'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['owner', 'updated_at'], name='assistant_a_owner_i_ca209c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assistant',
            unique_together={('owner', 'name', 'language', 'voice')},
        ),
    ]
