# Generated by Django 5.2.8 on 2025-11-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptchunk',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='transcripts/'),
        ),
        migrations.AlterField(
            model_name='transcriptchunk',
            name='chunk',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
