# Generated by Django 5.2.9 on 2026-01-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_alter_transcriptchunk_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='agent_type',
            field=models.CharField(choices=[('chat', 'Chat'), ('call', 'Call')], default='chat', max_length=100),
        ),
    ]
