# Generated by Django 5.2.9 on 2026-01-07 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0001_initial'),
        ('social', '0011_alter_instagramaccount_profile_picture'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='socialpostpublish',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='socialpostpublish',
            name='post',
        ),
        migrations.AddField(
            model_name='socialpost',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='hashtags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='platforms',
            field=models.ManyToManyField(blank=True, to='social.socialplatform'),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='post_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PostMediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='social_posts/media/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='publish.socialpost')),
            ],
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
        migrations.DeleteModel(
            name='SocialPostPublish',
        ),
    ]
