# Generated by Django 5.2.9 on 2026-01-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0003_mediadraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='page_access_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
