# Generated by Django 5.2.9 on 2026-01-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0005_comment_reaction_subcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
