# Generated by Django 6.0 on 2025-12-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profitlossreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profitlossreport',
            name='status',
            field=models.CharField(choices=[('Profit', 'Profit'), ('Loss', 'Loss'), ('approved', 'Approved')], default='draft', max_length=20),
        ),
    ]
