# Generated by Django 5.2.9 on 2025-12-23 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_invoice_product_receiver_remove_payment_customer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-created_at'], 'verbose_name': 'Income', 'verbose_name_plural': 'Incomes'},
        ),
        migrations.RemoveField(
            model_name='income',
            name='daily_income',
        ),
        migrations.RemoveField(
            model_name='income',
            name='monthly_income',
        ),
        migrations.RemoveField(
            model_name='income',
            name='total_income',
        ),
        migrations.RemoveField(
            model_name='income',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Income amount', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='source',
            field=models.CharField(default='Unknown', help_text='Income source, e.g., Salary, Freelance', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='income',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to=settings.AUTH_USER_MODEL),
        ),
    ]
