# Generated by Django 5.2.9 on 2025-12-23 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_income_options_remove_income_daily_income_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profitlossreport',
            name='net_profit',
        ),
    ]
