# Generated by Django 5.2.9 on 2025-12-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_sells'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sells',
            old_name='price',
            new_name='order_amount',
        ),
        migrations.AddField(
            model_name='sells',
            name='customer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sells',
            name='order_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
