# Generated by Django 5.2.9 on 2025-12-31 10:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_rename_price_customerrefund_order_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerRefund',
            new_name='Refund',
        ),
    ]
