# Generated by Django 5.2.9 on 2025-12-31 11:33

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_rename_customerrefund_refund'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=255)),
                ('payment_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_credit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='VoucherEntry',
        ),
        migrations.DeleteModel(
            name='VoucherType',
        ),
        migrations.AddIndex(
            model_name='debitcredit',
            index=models.Index(fields=['owner', 'customer_name'], name='account_deb_owner_i_24536e_idx'),
        ),
        migrations.AddIndex(
            model_name='debitcredit',
            index=models.Index(fields=['voucher_no'], name='account_deb_voucher_f81b4e_idx'),
        ),
    ]
