# Generated by Django 5.2.9 on 2025-12-31 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_debitcredit_delete_voucherentry_delete_vouchertype_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='debitcredit',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debitcredit',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='debitcredit',
            name='payment_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debitcredit',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='debitcredit',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='debitcredit',
            index=models.Index(fields=['invoice_no'], name='account_deb_invoice_f2c6de_idx'),
        ),
    ]
