# Generated by Django 5.2.9 on 2025-12-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_debitcredit_due_date_debitcredit_invoice_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitcredit',
            name='voucher_no',
            field=models.CharField(max_length=10),
        ),
    ]
