# Generated by Django 5.2.9 on 2025-12-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_debitcredit_voucher_no'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='debitcredit',
            name='account_deb_owner_i_24536e_idx',
        ),
        migrations.RemoveIndex(
            model_name='debitcredit',
            name='account_deb_voucher_f81b4e_idx',
        ),
        migrations.RemoveIndex(
            model_name='debitcredit',
            name='account_deb_invoice_f2c6de_idx',
        ),
        migrations.AlterField(
            model_name='debitcredit',
            name='payment_type',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10),
        ),
        migrations.AlterField(
            model_name='debitcredit',
            name='voucher_no',
            field=models.CharField(max_length=20),
        ),
    ]
