# Generated by Django 5.2.9 on 2025-12-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_remove_debitcredit_account_deb_owner_i_24536e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitcredit',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank')], max_length=10),
        ),
    ]
