# Generated by Django 5.2.9 on 2026-01-01 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_debitcredit_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profitlossreport',
            name='operating_expenses',
        ),
    ]
