# Generated by Django 5.2.9 on 2026-01-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_remove_profitlossreport_operating_expenses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profitlossreport',
            name='status',
        ),
        migrations.AddField(
            model_name='profitlossreport',
            name='net_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
