# Generated by Django 5.2.9 on 2026-01-01 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_remove_profitlossreport_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profitlossreport',
            name='gross_profit',
        ),
        migrations.RemoveField(
            model_name='profitlossreport',
            name='net_profit',
        ),
    ]
