# Generated by Django 5.2.9 on 2026-01-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_remove_profitlossreport_gross_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitcredit',
            name='entry_type',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], default='debit', max_length=10),
        ),
    ]
