# Generated by Django 5.2.9 on 2025-12-24 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentgateway', '0004_shurjopaypayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShurjopayPayment',
        ),
    ]
