# Generated by Django 5.2.8 on 2025-11-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topup',
            name='client_secret',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
