# Generated by Django 5.2.8 on 2025-11-23 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoice_discount'),
    ]

    operations = [
    ]
