# Generated by Django 5.2.8 on 2025-11-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_number', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='friendly_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
