# Generated by Django 6.0 on 2025-12-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=255)),
                ('page_name', models.CharField(max_length=255)),
                ('page_access_token', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('youtube', 'YouTube')], max_length=20)),
                ('user_access_token', models.TextField()),
                ('long_lived_token', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('refresh_expires_at', models.DateTimeField(blank=True, null=True)),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('other_token', models.TextField(blank=True, null=True)),
                ('other_expires_at', models.DateTimeField(blank=True, null=True)),
                ('fb_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ig_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('tw_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('yt_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('li_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('tk_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
