# Generated by Django 5.2.9 on 2025-12-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpage',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='facebookpage',
            name='category_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='facebookpage',
            name='tasks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
