# Generated by Django 5.2.9 on 2025-12-18 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_facebookpage_category_facebookpage_category_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookpage',
            name='social_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facebook_pages', to='social.socialaccount'),
        ),
    ]
