# Generated by Django 5.2.9 on 2025-12-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_socialplatform'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialplatform',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
