# Generated by Django 5.2.9 on 2025-12-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_socialplatform_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
