# Generated by Django 5.2.9 on 2026-01-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_instagramaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramaccount',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
