# Generated by Django 5.2.9 on 2026-01-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_alter_instagramaccount_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramaccount',
            name='page_id',
            field=models.TextField(),
        ),
    ]
