# Generated by Django 5.2.9 on 2026-01-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_alter_instagramaccount_page_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramaccount',
            name='profile_picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
