# Generated by Django 5.2.9 on 2026-01-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_alter_instagramaccount_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppBusinessAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(max_length=100)),
                ('business_name', models.CharField(max_length=255)),
                ('waba_id', models.CharField(max_length=100)),
                ('waba_name', models.CharField(max_length=255)),
                ('phone_number_id', models.CharField(max_length=100)),
                ('display_phone_number', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
