# Generated by Django 5.2.9 on 2026-02-07 06:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_alter_socialaccount_platform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('widget', 'Widget')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='whatsappbusinessaccount',
            unique_together={('user', 'waba_id', 'phone_number_id')},
        ),
    ]
