# Generated by Django 5.2.9 on 2025-12-18 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social', '0004_alter_facebookpage_social_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('profile_pic_url', models.URLField(blank=True, null=True)),
                ('personal_info', models.JSONField(blank=True, default=list)),
                ('external_user_id', models.CharField(max_length=100)),
                ('external_username', models.CharField(blank=True, max_length=255, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='social.socialaccount')),
            ],
            options={
                'unique_together': {('platform', 'social_account', 'external_user_id')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sender_type', models.CharField(choices=[('customer', 'Customer'), ('page', 'Page'), ('bot', 'Bot'), ('marchant', 'Marchant'), ('system', 'System')], max_length=10)),
                ('text', models.TextField(blank=True)),
                ('attachment_url', models.URLField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
