# Generated by Django 5.2.9 on 2025-12-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='page_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
