# Generated by Django 5.2.9 on 2025-12-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_page_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('page', 'Page'), ('assistant', 'Assistant'), ('marchant', 'Marchant'), ('system', 'System')], max_length=10),
        ),
    ]
