# Generated by Django 5.2.9 on 2026-01-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_sender_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_bot_active',
            field=models.BooleanField(default=True),
        ),
    ]
