# Generated by Django 5.2.9 on 2026-01-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversation_is_bot_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('bot', 'Bot'), ('seller', 'Seller'), ('vendor', 'Vendor'), ('system', 'System')], max_length=10),
        ),
    ]
