# Generated by Django 5.2.9 on 2026-01-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_message_sender_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment_url',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
