# Generated by Django 5.2.9 on 2026-01-21 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_message_attachment_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='attachment_url',
            new_name='attachments',
        ),
    ]
