# Generated by Django 5.2.9 on 2026-01-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_rename_attachment_url_message_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachments',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
