# Generated by Django 5.2.9 on 2026-01-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_message_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_profile_pic',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='personal_info',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
