# Generated by Django 5.2.9 on 2026-01-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_message_sender_metadata_message_sender_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='profile_pic_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
