# Generated by Django 5.2.9 on 2026-01-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_conversation_profile_pic_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender_profile_pic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
