# Generated by Django 5.2.9 on 2026-02-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_message_sender_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('widget', 'Widget'), ('widget_bot', 'Widget Bot')], max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('widget', 'Widget'), ('widget_bot', 'Widget Bot')], max_length=20),
        ),
    ]
